/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Advanced: typeof import('./src/components/gsap/advanced/index.vue')['default']
    Basic: typeof import('./src/components/gsap/basic/index.vue')['default']
    BasicAnimation: typeof import('./src/components/gsap/basic/BasicAnimation.vue')['default']
    FadeInScroll: typeof import('./src/components/gsap/scroll/FadeInScroll.vue')['default']
    Footer: typeof import('./src/components/layout/Footer.vue')['default']
    GsapAnimation: typeof import('./src/components/gsap/GsapAnimation.vue')['default']
    GsapContainer: typeof import('./src/components/gsap/GsapContainer.vue')['default']
    GsapMotionPath: typeof import('./src/components/gsap/GsapMotionPath.vue')['default']
    GsapScrollTrigger: typeof import('./src/components/gsap/GsapScrollTrigger.vue')['default']
    GsapText: typeof import('./src/components/gsap/GsapText.vue')['default']
    GsapTimeline: typeof import('./src/components/gsap/GsapTimeline.vue')['default']
    GsapTimelineItem: typeof import('./src/components/gsap/GsapTimelineItem.vue')['default']
    HoverAnimation: typeof import('./src/components/gsap/basic/HoverAnimation.vue')['default']
    MobileMenu: typeof import('./src/components/layout/MobileMenu.vue')['default']
    MorphAnimation: typeof import('./src/components/gsap/advanced/MorphAnimation.vue')['default']
    Navbar: typeof import('./src/components/layout/Navbar.vue')['default']
    ParallaxScroll: typeof import('./src/components/gsap/scroll/ParallaxScroll.vue')['default']
    PathAnimation: typeof import('./src/components/gsap/advanced/PathAnimation.vue')['default']
    PhysicsAnimation: typeof import('./src/components/gsap/advanced/PhysicsAnimation.vue')['default']
    ProgressIndicator: typeof import('./src/components/gsap/scroll/ProgressIndicator.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollAnimations: typeof import('./src/components/gsap/scroll/ScrollAnimations.vue')['default']
    SideMenu: typeof import('./src/components/layout/SideMenu.vue')['default']
    TextAnimation: typeof import('./src/components/gsap/basic/TextAnimation.vue')['default']
    ThreeDAnimation: typeof import('./src/components/gsap/advanced/ThreeDAnimation.vue')['default']
    TimelineAnimation: typeof import('./src/components/gsap/basic/TimelineAnimation.vue')['default']
    TimelineScroll: typeof import('./src/components/gsap/scroll/TimelineScroll.vue')['default']
  }
}
